Religion.create(name: 'Catholic')
Religion.create(name: 'Anglican')
Religion.create(name: 'Protestant')
Religion.create(name: 'Mormon')
Religion.create(name: 'Jewish')
Religion.create(name: 'Muslim')
Religion.create(name: 'Buddhist')
Religion.create(name: 'Hindu')
Drug.create(name: 'Alcohol')
Drug.create(name: 'Heroin/Other Opiates')
Drug.create(name: 'Cocaine/Crack')
Drug.create(name: 'Meth/Other Amphetamines')
Drug.create(name: 'Marijuana')
Drug.create(name: 'Ecstasy/Hallucinogens')
Drug.create(name: 'Inhalants')
Drug.create(name: 'Prescription Drugs')
Insurer.create(name: 'Aetna')
Insurer.create(name: 'Alliant Health Plans')
Insurer.create(name: 'Allstate Insurance Company')
Insurer.create(name: 'American Family Insurance')
Insurer.create(name: 'American Medical Security Life Insurance Company')
Insurer.create(name: 'American National Insurance Company')
Insurer.create(name: 'Anthem')
Insurer.create(name: 'Assurant')
Insurer.create(name: 'Asuris Northwest Health')
Insurer.create(name: 'Beech Street')
Insurer.create(name: 'Blue Cross and Blue Shield Association')
Insurer.create(name: 'Celtic Insurance Co.')
Insurer.create(name: 'CIGNA')
Insurer.create(name: 'Clear Choice Health Plan')
Insurer.create(name: 'Community First')
Insurer.create(name: 'Community Health Plan of Washington')
Insurer.create(name: 'Continental General')
Insurer.create(name: 'Coventry Health care')
Insurer.create(name: 'Fortis')
Insurer.create(name: 'Fox insurance company')
Insurer.create(name: 'Golden Rule Insurance Company')
Insurer.create(name: 'Group Health Cooperative')
Insurer.create(name: 'Group Health Inc.')
Insurer.create(name: 'Harvard Community Health Plan')
Insurer.create(name: 'Health Net of Arizona')
Insurer.create(name: 'Health Net of Oregon')
Insurer.create(name: 'Health Partners')
Insurer.create(name: 'Health Plan of Nevada')
Insurer.create(name: 'HealthMarkets')
Insurer.create(name: 'Humana Inc.')
Insurer.create(name: 'Insurance Services of America')
Insurer.create(name: 'Intermountain Health Care')
Insurer.create(name: 'Kaiser Permanente')
Insurer.create(name: 'LifeWise Health Plan of Arizona')
Insurer.create(name: 'LifeWise Health Plan of Oregon')
Insurer.create(name: 'LifeWise Health Plan of Washington')
Insurer.create(name: 'Medica of Minnesota')
Insurer.create(name: 'Medical Mutual')
Insurer.create(name: 'Membercare Insurance')
Insurer.create(name: 'Out of Network Provider')
Insurer.create(name: 'Oxford Health Plans, Inc.')
Insurer.create(name: 'Principal Financial Group')
Insurer.create(name: 'Shelter Insurance Companies')
Insurer.create(name: 'UNICARE')
Insurer.create(name: 'United Health Care')
Insurer.create(name: 'Vista Healthplan of South Florida')
Insurer.create(name: 'Wellpoint')
Insurer.create(name: 'World Insurance')
TreatmentType.create(name: 'Inpatient', description: 'In-patient (sleeping at facility)')
TreatmentType.create(name: 'Outpatient', description: 'Out-patient (sleeping at home)')